import { createHash } from 'node:crypto'
import { createReadStream } from 'node:fs'
import { open } from 'node:fs/promises'
import { parseTimestamp } from './metadataParser'

/** Bump when the summary shape or extraction rules change (invalidates cache). */
export const PARSER_VERSION = 5

const MAX_TEXT = 2000
const MAX_LINE_BYTES = 128 * 1024 * 1024
const HEAD_BYTES = 4096
const RECENT_ID_WINDOW = 16

/**
 * Everything the app needs from a transcript, small enough to cache.
 * Accumulative, so parsing can resume from a byte offset when a transcript
 * only grew (Claude Code appends to JSONL files).
 */
export interface TranscriptSummary {
  sessionIds: string[]
  firstUserMessage?: string
  lastUserMessage?: string
  lastPrompt?: string
  customTitle?: string
  aiTitle?: string
  agentName?: string
  summary?: string
  firstTimestamp?: number
  lastTimestamp?: number
  model?: string
  models: string[]
  userMessageCount: number
  assistantMessageCount: number
  /** Distinct assistant API message ids (see applyRecord). */
  recentAssistantIds: string[]
  toolUseCount: number
  lineCount: number
  invalidLineCount: number
  cwd?: string
  gitBranch?: string
  version?: string
  entrypoint?: string
}

export function emptySummary(): TranscriptSummary {
  return {
    sessionIds: [],
    models: [],
    userMessageCount: 0,
    assistantMessageCount: 0,
    recentAssistantIds: [],
    toolUseCount: 0,
    lineCount: 0,
    invalidLineCount: 0
  }
}

type Rec = Record<string, unknown>

function str(v: unknown): string | undefined {
  return typeof v === 'string' && v.trim() !== '' ? v : undefined
}

function clip(text: string): string {
  return text.length > MAX_TEXT ? text.slice(0, MAX_TEXT - 1) + '…' : text
}

/** Wrapper tags injected by Claude Code / IDEs that are not the user's words. */
const STRIP_BLOCKS = [
  'system-reminder',
  'ide_selection',
  'ide_opened_file',
  'ide_diagnostics',
  'user-prompt-submit-hook',
  'command-message',
  'local-command-caveat'
]
const NON_PROMPT_PREFIXES = [
  '<local-command-stdout',
  '<local-command-stderr',
  '<bash-stdout',
  '<bash-stderr',
  '<task-notification',
  '[Request interrupted by user',
  'Caveat: The messages below were generated by the user while running local commands'
]

/**
 * Turn raw user content into the prompt the user actually typed, or
 * undefined if the message is not a meaningful prompt.
 */
export function cleanPromptText(raw: string): string | undefined {
  let text = raw.trim()
  if (!text) return undefined

  const command = /<command-name>([^<]*)<\/command-name>/.exec(text)
  if (command) {
    const args = /<command-args>([\s\S]*?)<\/command-args>/.exec(text)?.[1]?.trim()
    const name = command[1].trim()
    return name ? clip(args ? `${name} ${args}` : name) : undefined
  }
  const bash = /<bash-input>([\s\S]*?)<\/bash-input>/.exec(text)
  if (bash) return clip(`! ${bash[1].trim()}`)

  if (NON_PROMPT_PREFIXES.some((p) => text.startsWith(p))) return undefined

  for (const tag of STRIP_BLOCKS) {
    text = text.replace(new RegExp(`<${tag}(?:\\s[^>]*)?>[\\s\\S]*?</${tag}>`, 'g'), '')
  }
  text = text.replace(/<\/?pasted_content(?:\s[^>]*)?>/g, '').trim()
  return text ? clip(text) : undefined
}

/** Extract the meaningful prompt text from a `type: "user"` record. */
export function extractUserText(rec: Rec): string | undefined {
  if (rec.isMeta === true || rec.isSidechain === true || rec.isCompactSummary === true) return undefined
  if (rec.isVisibleInTranscriptOnly === true || rec.toolUseResult !== undefined) return undefined
  const message = rec.message as Rec | undefined
  if (!message || typeof message !== 'object') return undefined
  if (message.role !== undefined && message.role !== 'user') return undefined

  const content = message.content
  if (typeof content === 'string') return cleanPromptText(content)
  if (Array.isArray(content)) {
    // Only text blocks count; tool_result / image blocks are not prompts.
    const texts: string[] = []
    for (const block of content) {
      if (!block || typeof block !== 'object') continue
      const b = block as Rec
      if (b.type === 'text' && typeof b.text === 'string') {
        const cleaned = cleanPromptText(b.text)
        if (cleaned) texts.push(cleaned)
      }
    }
    return texts.length ? clip(texts.join('\n')) : undefined
  }
  return undefined
}

/** Fold one JSONL record into the summary (pure, exported for tests). */
export function applyRecord(s: TranscriptSummary, rec: unknown): void {
  if (!rec || typeof rec !== 'object' || Array.isArray(rec)) return
  const r = rec as Rec

  const ts = parseTimestamp(r.timestamp)
  if (ts !== undefined) {
    if (s.firstTimestamp === undefined || ts < s.firstTimestamp) s.firstTimestamp = ts
    if (s.lastTimestamp === undefined || ts > s.lastTimestamp) s.lastTimestamp = ts
  }
  const sid = str(r.sessionId)
  if (sid && s.sessionIds.length < 8 && !s.sessionIds.includes(sid)) s.sessionIds.push(sid)
  if (!s.cwd && str(r.cwd)) s.cwd = r.cwd as string
  if (str(r.gitBranch)) s.gitBranch = r.gitBranch as string
  if (str(r.version)) s.version = r.version as string
  if (!s.entrypoint && str(r.entrypoint)) s.entrypoint = r.entrypoint as string

  switch (r.type) {
    case 'user': {
      const text = extractUserText(r)
      if (text) {
        s.userMessageCount++
        if (s.firstUserMessage === undefined) s.firstUserMessage = text
        s.lastUserMessage = text
      }
      break
    }
    case 'assistant': {
      if (r.isSidechain === true) break
      const message = (r.message ?? {}) as Rec
      const id = str(message.id)
      // Claude Code writes one record per content block, all sharing the API
      // message id, sometimes interleaved with tool results. Count each id once
      // (a small window of recent ids is enough; blocks of one message are close).
      if (!id || !s.recentAssistantIds.includes(id)) {
        s.assistantMessageCount++
        if (id) {
          s.recentAssistantIds.push(id)
          if (s.recentAssistantIds.length > RECENT_ID_WINDOW) s.recentAssistantIds.shift()
        }
      }
      if (Array.isArray(message.content)) {
        for (const block of message.content) {
          if (block && typeof block === 'object' && (block as Rec).type === 'tool_use') s.toolUseCount++
        }
      }
      const model = str(message.model)
      if (model && model !== '<synthetic>') {
        s.model = model
        if (!s.models.includes(model) && s.models.length < 12) s.models.push(model)
      }
      break
    }
    case 'ai-title':
      if (str(r.aiTitle)) s.aiTitle = r.aiTitle as string
      break
    case 'custom-title':
      s.customTitle = str(r.customTitle)
      break
    case 'agent-name':
      if (str(r.agentName)) s.agentName = r.agentName as string
      break
    case 'summary':
      if (str(r.summary)) s.summary = r.summary as string
      break
    case 'last-prompt': {
      const p = typeof r.lastPrompt === 'string' ? cleanPromptText(r.lastPrompt) : undefined
      if (p) s.lastPrompt = p
      break
    }
  }
}

export interface JsonlLine {
  text: string
  /** Absolute byte offset just after this line (and its newline, if any). */
  end: number
  /** Last line of the file without a trailing newline (may be mid-write). */
  partial: boolean
}

/**
 * Stream a JSONL file line by line from a byte offset. Lines are split on
 * the raw 0x0A byte (never inside a UTF-8 multi-byte sequence) and decoded
 * whole, so Vietnamese and other non-ASCII text is never mangled even when a
 * character straddles a chunk boundary.
 */
export async function* readJsonlLines(
  filePath: string,
  opts: { start?: number; chunkSize?: number } = {}
): AsyncGenerator<JsonlLine> {
  const start = opts.start ?? 0
  const stream = createReadStream(filePath, { start, highWaterMark: opts.chunkSize ?? 1024 * 1024 })
  let pending: Buffer[] = []
  let pendingLen = 0
  let chunkStart = start
  let first = start === 0
  const decode = (buf: Buffer): string => {
    let b = buf
    if (first) {
      first = false
      if (b.length >= 3 && b[0] === 0xef && b[1] === 0xbb && b[2] === 0xbf) b = b.subarray(3)
    }
    if (b.length && b[b.length - 1] === 0x0d) b = b.subarray(0, b.length - 1)
    return b.toString('utf8')
  }

  for await (const chunk of stream as AsyncIterable<Buffer>) {
    let pos = 0
    for (;;) {
      const nl = chunk.indexOf(0x0a, pos)
      if (nl === -1) {
        if (pos < chunk.length) {
          pending.push(chunk.subarray(pos))
          pendingLen += chunk.length - pos
        }
        break
      }
      let line = chunk.subarray(pos, nl)
      if (pendingLen) {
        line = Buffer.concat([...pending, line], pendingLen + line.length)
        pending = []
        pendingLen = 0
      }
      const end = chunkStart + nl + 1
      if (line.length <= MAX_LINE_BYTES) yield { text: decode(line), end, partial: false }
      else yield { text: '', end, partial: false }
      pos = nl + 1
    }
    chunkStart += chunk.length
  }
  if (pendingLen) {
    const line = Buffer.concat(pending, pendingLen)
    yield { text: line.length <= MAX_LINE_BYTES ? decode(line) : '', end: chunkStart, partial: true }
  }
}

export interface ParseResult {
  summary: TranscriptSummary
  /** Offset after the last fully consumed line; resume point for next parse. */
  bytesParsed: number
}

/**
 * Parse (or continue parsing) a transcript. When `resume` is given, parsing
 * starts at `resume.bytesParsed` with a copy of `resume.summary`.
 */
export async function parseTranscriptFile(
  filePath: string,
  opts: { resume?: ParseResult; chunkSize?: number } = {}
): Promise<ParseResult> {
  const summary: TranscriptSummary = opts.resume ? structuredClone(opts.resume.summary) : emptySummary()
  let bytesParsed = opts.resume?.bytesParsed ?? 0

  for await (const line of readJsonlLines(filePath, { start: bytesParsed, chunkSize: opts.chunkSize })) {
    if (!line.text.trim()) {
      if (!line.partial) bytesParsed = line.end
      continue
    }
    let rec: unknown
    try {
      rec = JSON.parse(line.text)
    } catch {
      // A trailing partial line is probably still being written: leave it for next time.
      if (line.partial) break
      summary.lineCount++
      summary.invalidLineCount++
      bytesParsed = line.end
      continue
    }
    summary.lineCount++
    applyRecord(summary, rec)
    bytesParsed = line.end
  }
  return { summary, bytesParsed }
}

/**
 * SHA-1 of the first min(4 KiB, parsedBytes) bytes. Only the already parsed
 * prefix is hashed, so appending never changes it while a rewrite does.
 */
export async function readHeadHash(filePath: string, parsedBytes: number): Promise<string> {
  const len = Math.max(0, Math.min(HEAD_BYTES, parsedBytes))
  const handle = await open(filePath, 'r')
  try {
    const buf = Buffer.alloc(len)
    const { bytesRead } = len ? await handle.read(buf, 0, len, 0) : { bytesRead: 0 }
    return createHash('sha1').update(buf.subarray(0, bytesRead)).digest('hex')
  } finally {
    await handle.close()
  }
}

/**
 * Read the `sessionId` declared in the first records of a JSONL file
 * (used to attribute legacy project-level agent-*.jsonl logs).
 */
export async function readDeclaredSessionId(filePath: string, maxLines = 5): Promise<string | undefined> {
  return readDeclaredField(filePath, 'sessionId', maxLines)
}

/** First non-empty string value of `field` in the first few records of a JSONL file. */
export async function readDeclaredField(filePath: string, field: string, maxLines = 5): Promise<string | undefined> {
  let n = 0
  for await (const line of readJsonlLines(filePath, { chunkSize: 64 * 1024 })) {
    if (++n > maxLines) break
    try {
      const rec = JSON.parse(line.text) as Rec
      const value = str(rec?.[field])
      if (value) return value
    } catch {
      /* ignore */
    }
  }
  return undefined
}
