/**
 * Types shared by the main process, preload and renderer.
 *
 * Everything here must be structured-clone friendly (plain objects, arrays,
 * strings, numbers, booleans). Timestamps are epoch milliseconds.
 */

export type SessionStatus = 'active' | 'archived' | 'transcript-only' | 'metadata-only' | 'orphan'

/** Where a session record originates from. */
export type SessionKind =
  /** Claude Desktop "Code" session: has a local_*.json metadata file. */
  | 'desktop'
  /** Claude Code CLI / IDE session: only a <uuid>.jsonl transcript. */
  | 'cli'
  /** A <uuid>/ session data directory with neither transcript nor metadata. */
  | 'orphan'

/**
 * The raw `title` field of a Claude Desktop metadata file, preserved exactly
 * so the UI can show the difference between "missing", null and "".
 */
export type RawTitle =
  | { kind: 'missing' }
  | { kind: 'null' }
  | { kind: 'empty'; value: string }
  | { kind: 'string'; value: string }
  | { kind: 'invalid'; type: string }

export type TitleSource =
  | 'metadata'
  | 'custom-title'
  | 'ai-title'
  | 'summary'
  | 'first-prompt'
  | 'last-prompt'
  | 'untitled'

/** How a session is archived, if at all. */
export type ArchiveSource =
  /** `isArchived: true` in the Claude Desktop metadata file. */
  | 'desktop-metadata'
  /** Archived only inside this app (Claude Code CLI has no archive flag). */
  | 'app-local'

export interface LiveSessionRef {
  pid: number
  status?: string
  name?: string
  entrypoint?: string
}

export interface ClaudeSession {
  /** Internal stable ID assigned by the scanner. The only ID the renderer may send back. */
  id: string
  kind: SessionKind
  status: SessionStatus

  displayTitle: string
  titleSource: TitleSource
  /** Raw `title` from Claude Desktop metadata (only for desktop sessions). */
  rawTitle?: RawTitle
  /** `custom-title` set via /rename or the IDE (transcript or custom-title.json). */
  customTitle?: string
  /** `ai-title` generated by Claude Code. */
  aiTitle?: string
  /** Legacy `summary` record. */
  summary?: string

  /** Claude Desktop session ID (`local_…`). */
  desktopSessionId?: string
  /** Claude Code session UUID (= transcript file name). */
  cliSessionId?: string
  /** Older transcripts of the same Desktop session (`priorCliSessionIds`). */
  priorCliSessionIds: string[]

  projectPath?: string
  projectName: string
  /** Key used for grouping/filtering by project. */
  projectKey: string
  /** Name of the folder under ~/.claude/projects. */
  projectDirName?: string

  metadataFile?: string
  transcriptFile?: string
  extraTranscriptFiles: string[]
  sessionDataDirectory?: string
  fileHistoryDirectory?: string
  sessionEnvDirectory?: string
  legacySubagentLogs: string[]

  archived: boolean
  archiveSource?: ArchiveSource

  createdAt?: number
  updatedAt?: number

  transcriptSize?: number
  metadataSize?: number
  sessionDataSize?: number
  otherSize?: number
  totalSize: number

  model?: string
  models: string[]

  firstUserMessage?: string
  lastUserMessage?: string
  lastPrompt?: string
  userMessageCount?: number
  assistantMessageCount?: number

  gitBranch?: string
  claudeVersion?: string
  entrypoint?: string

  hasMetadata: boolean
  hasTranscript: boolean
  /** Remote (SSH/WSL) Desktop session: transcript is not on this machine. */
  remoteKind?: 'ssh' | 'wsl'

  /** Set when a running Claude Code process currently owns this session. */
  live?: LiveSessionRef

  problems: string[]
}

export interface SessionDetails {
  session: ClaudeSession
  /** Pretty-printed metadata JSON, if a metadata file exists and is readable. */
  rawMetadata?: string
  rawMetadataError?: string
  /** Tombstone files present for this session's IDs (informational). */
  tombstones: string[]
}

// ---------------------------------------------------------------------------
// Storage discovery
// ---------------------------------------------------------------------------

export interface DesktopRootInfo {
  /** Canonical path of a `claude-code-sessions` directory. */
  path: string
  source: 'msix' | 'appdata' | 'other'
  /** `Claude` or `Claude-3p`. */
  variant: string
  packageName?: string
  sessionFiles: number
  tombstones: number
  archiveIndexes: number
}

export interface CandidatePath {
  path: string
  exists: boolean
  note?: string
}

export interface StorageRoots {
  claudeHome: string
  projectsRoot: string | null
  fileHistoryRoot: string | null
  sessionEnvRoot: string | null
  liveSessionsDir: string | null
  desktopRoots: DesktopRootInfo[]
  candidates: CandidatePath[]
}

export interface ScanStats {
  transcripts: number
  transcriptsParsed: number
  transcriptsIncremental: number
  transcriptsFromCache: number
  subagentLogsExcluded: number
  legacySubagentLogs: number
  sessionDataDirs: number
  orphanDirs: number
  metadataFiles: number
  metadataInvalid: number
  tombstones: number
  ignoredEntries: number
}

export interface ScanIssue {
  path?: string
  message: string
}

export interface ScanSnapshot {
  sessions: ClaudeSession[]
  scannedAt: number
  durationMs: number
  roots: StorageRoots
  stats: ScanStats
  issues: ScanIssue[]
}

export interface ProjectUsage {
  projectKey: string
  projectName: string
  projectPath?: string
  sessions: number
  totalSize: number
}

export interface StorageInfo {
  totalSessions: number
  active: number
  archived: number
  transcriptOnly: number
  metadataOnly: number
  orphan: number
  problems: number
  totalSize: number
  transcriptBytes: number
  sessionDataBytes: number
  otherBytes: number
  topProjects: ProjectUsage[]
  largestSessions: Array<Pick<ClaudeSession, 'id' | 'displayTitle' | 'projectName' | 'totalSize' | 'status'>>
  roots: StorageRoots
  cachePath: string
  scannedAt: number
}

// ---------------------------------------------------------------------------
// Process safety
// ---------------------------------------------------------------------------

export type ClaudeProcessKind = 'desktop' | 'claude-code' | 'unknown'

export interface ClaudeProcessInfo {
  pid: number
  name: string
  executablePath?: string
  kind: ClaudeProcessKind
}

export interface LiveCliSession {
  pid: number
  sessionId: string
  cwd?: string
  status?: string
  name?: string
  entrypoint?: string
  alive: boolean
}

export interface ProcessStatus {
  checkedAt: number
  supported: boolean
  /** Claude Desktop (or an unidentifiable Claude process) is running. */
  desktopRunning: boolean
  desktopProcesses: ClaudeProcessInfo[]
  claudeCodeProcesses: ClaudeProcessInfo[]
  unknownProcesses: ClaudeProcessInfo[]
  liveSessions: LiveCliSession[]
  error?: string
}

// ---------------------------------------------------------------------------
// Actions
// ---------------------------------------------------------------------------

export type ActionErrorCode =
  | 'CLAUDE_RUNNING'
  | 'SESSION_IN_USE'
  | 'NOT_FOUND'
  | 'NOT_SUPPORTED'
  | 'INVALID_INPUT'
  | 'PATH_REJECTED'
  | 'CHANGED_ON_DISK'
  | 'IO_ERROR'
  | 'CANCELLED'

export interface ActionResult {
  ok: boolean
  message: string
  code?: ActionErrorCode
  dryRun?: boolean
}

export interface BulkActionResult {
  ok: boolean
  message: string
  results: Array<{ id: string; title: string } & ActionResult>
}

export type PlanItemKind =
  | 'metadata'
  | 'transcript'
  | 'session-data'
  | 'subagent-log'
  | 'file-history'
  | 'session-env'
  | 'tombstone'
  | 'archive-index'

export type PlanAction = 'delete-file' | 'delete-directory' | 'create-file' | 'update-file'

export interface DeletePlanItem {
  kind: PlanItemKind
  action: PlanAction
  path: string
  sizeBytes?: number
  fileCount?: number
  note?: string
}

export interface SessionDeletePlan {
  sessionId: string
  displayTitle: string
  status: SessionStatus
  items: DeletePlanItem[]
  totalBytes: number
  /** When set, this session cannot be deleted right now. */
  blockedReason?: string
  blockedCode?: ActionErrorCode
  warnings: string[]
}

export interface DeletePlan {
  token: string
  createdAt: number
  dryRun: boolean
  bulk: boolean
  /** Sessions that will be deleted. */
  sessions: SessionDeletePlan[]
  /** Sessions that were requested but are blocked and will be skipped. */
  blocked: SessionDeletePlan[]
  /** Global reason that blocks everything (e.g. Claude Desktop running). */
  globalBlockedReason?: string
  globalBlockedCode?: ActionErrorCode
  totalBytes: number
  totalItems: number
  /** Phrases accepted in the confirmation box. */
  confirmationPhrases: string[]
}

export type DeleteItemOutcome = 'deleted' | 'created' | 'updated' | 'missing' | 'failed' | 'skipped' | 'dry-run'

export interface DeleteItemResult extends DeletePlanItem {
  outcome: DeleteItemOutcome
  error?: string
}

export interface SessionDeleteResult {
  sessionId: string
  displayTitle: string
  outcome: 'deleted' | 'partial' | 'failed' | 'skipped' | 'dry-run'
  items: DeleteItemResult[]
  error?: string
}

export interface DeleteResult {
  ok: boolean
  partial: boolean
  dryRun: boolean
  code?: ActionErrorCode
  message: string
  sessions: SessionDeleteResult[]
}

export type ExportFormat = 'jsonl' | 'info' | 'markdown'

export interface ExportResult {
  ok: boolean
  message: string
  files: string[]
  errors: string[]
  cancelled?: boolean
}

// ---------------------------------------------------------------------------
// Settings / app info
// ---------------------------------------------------------------------------

export type RefreshMode = 'manual' | 'watch' | 'interval'

export interface AppSettings {
  refreshMode: RefreshMode
  refreshIntervalSec: number
  showRawPaths: boolean
  debugMode: boolean
}

export interface AppInfo {
  name: string
  version: string
  dryRun: boolean
  isPackaged: boolean
  platform: string
  userDataPath: string
  cachePath: string
  logPath: string
  electronVersion: string
}

export interface LogEntry {
  time: number
  level: 'debug' | 'info' | 'warn' | 'error'
  message: string
}
