/**
 * Types shared by the main process, preload and renderer.
 *
 * Everything here must be structured-clone friendly (plain objects, arrays,
 * strings, numbers, booleans). Timestamps are epoch milliseconds.
 */

export type SessionStatus = 'active' | 'archived' | 'transcript-only' | 'metadata-only' | 'orphan'

/** Where a session record originates from. */
export type SessionKind =
  /** Claude Desktop "Code" session: has a local_*.json metadata file. */
  | 'desktop'
  /** Claude Code CLI / IDE session: only a <uuid>.jsonl transcript. */
  | 'cli'
  /** A <uuid>/ session data directory with neither transcript nor metadata. */
  | 'orphan'

/**
 * The raw `title` field of a Claude Desktop metadata file, preserved exactly
 * so the UI can show the difference between "missing", null and "".
 */
export type RawTitle =
  | { kind: 'missing' }
  | { kind: 'null' }
  | { kind: 'empty'; value: string }
  | { kind: 'string'; value: string }
  | { kind: 'invalid'; type: string }

export type TitleSource =
  | 'metadata'
  | 'custom-title'
  | 'ai-title'
  | 'summary'
  | 'first-prompt'
  | 'last-prompt'
  | 'untitled'

/** How a session is archived, if at all. */
/**
 * How a running Claude Code process holds a session (from the `status` in
 * ~/.claude/sessions/<pid>.json): `running` = busy generating, `idle` =
 * attached but idle, `in-use` = attached in any other state (waiting for
 * input/permission, unknown). Every state blocks deletion.
 */
export type LiveState = 'running' | 'idle' | 'in-use'

export interface LiveSessionRef {
  pid: number
  state: LiveState
  status?: string
  name?: string
  entrypoint?: string
}

/** Where the canonical project path of a session came from. */
export type ProjectSource =
  | 'metadata-cwd'
  | 'transcript-cwd'
  | 'owner-session'
  | 'folder-records'
  | 'decoded-folder-name'
  | 'unresolved'

export interface ClaudeSession {
  /** Internal stable ID assigned by the scanner. The only ID the renderer may send back. */
  id: string
  kind: SessionKind
  status: SessionStatus

  displayTitle: string
  titleSource: TitleSource
  /** Raw `title` from Claude Desktop metadata (only for desktop sessions). */
  rawTitle?: RawTitle
  /** `custom-title` set via /rename or the IDE (transcript or custom-title.json). */
  customTitle?: string
  /** `ai-title` generated by Claude Code. */
  aiTitle?: string
  /** Legacy `summary` record. */
  summary?: string

  /** Claude Desktop session ID (`local_…`). */
  desktopSessionId?: string
  /** Claude Code session UUID (= transcript file name). */
  cliSessionId?: string
  /** Older transcripts of the same Desktop session (`priorCliSessionIds`). */
  priorCliSessionIds: string[]

  /** Canonical workspace path (real cwd). Never part of any delete plan. */
  projectPath?: string
  projectName: string
  /** Key used for grouping/filtering by project (derived from the canonical path). */
  projectKey: string
  projectSource: ProjectSource
  /** Encoded folder name under ~/.claude/projects (storage locator only). */
  projectDirName?: string
  /** Full path of that Claude storage folder (never deleted as a whole). */
  projectStorageDir?: string

  metadataFile?: string
  transcriptFile?: string
  extraTranscriptFiles: string[]
  sessionDataDirectory?: string
  /** Same-UUID session folders written while the session's cwd was elsewhere. */
  extraSessionDataDirectories: string[]
  fileHistoryDirectory?: string
  sessionEnvDirectory?: string
  legacySubagentLogs: string[]

  /** Claude Desktop's own archive flag (`isArchived` in metadata). */
  archived: boolean
  /** Hidden only inside this manager; Claude's files and archive state are untouched. */
  hiddenInManager: boolean

  createdAt?: number
  updatedAt?: number

  transcriptSize?: number
  metadataSize?: number
  sessionDataSize?: number
  otherSize?: number
  totalSize: number

  model?: string
  models: string[]

  firstUserMessage?: string
  lastUserMessage?: string
  lastPrompt?: string
  /** Meaningful user prompts (excludes tool results, meta and command output). */
  userMessageCount?: number
  /** Distinct assistant API messages (message IDs); one per model step, incl. tool-use steps. */
  assistantMessageCount?: number
  /** tool_use blocks issued by the assistant. */
  toolUseCount?: number
  /** Non-empty JSONL records in the transcript. */
  transcriptRecordCount?: number

  gitBranch?: string
  claudeVersion?: string
  entrypoint?: string

  hasMetadata: boolean
  hasTranscript: boolean
  /** Remote (SSH/WSL) Desktop session: transcript is not on this machine. */
  remoteKind?: 'ssh' | 'wsl'

  /** Set when a running Claude Code process currently owns this session. */
  live?: LiveSessionRef

  problems: string[]
}

export interface SessionDetails {
  session: ClaudeSession
  /** Pretty-printed metadata JSON, if a metadata file exists and is readable. */
  rawMetadata?: string
  rawMetadataError?: string
  /** Tombstone files present for this session's IDs (informational). */
  tombstones: string[]
}

// ---------------------------------------------------------------------------
// Storage discovery
// ---------------------------------------------------------------------------

export interface DesktopRootInfo {
  /** Canonical path of a `claude-code-sessions` directory. */
  path: string
  source: 'msix' | 'appdata' | 'other'
  /** `Claude` or `Claude-3p`. */
  variant: string
  packageName?: string
  sessionFiles: number
  tombstones: number
  archiveIndexes: number
}

export interface CandidatePath {
  path: string
  exists: boolean
  note?: string
}

export interface StorageRoots {
  claudeHome: string
  projectsRoot: string | null
  fileHistoryRoot: string | null
  sessionEnvRoot: string | null
  liveSessionsDir: string | null
  desktopRoots: DesktopRootInfo[]
  candidates: CandidatePath[]
}

export interface ScanStats {
  transcripts: number
  transcriptsParsed: number
  transcriptsIncremental: number
  transcriptsFromCache: number
  subagentLogsExcluded: number
  legacySubagentLogs: number
  sessionDataDirs: number
  orphanDirs: number
  metadataFiles: number
  metadataInvalid: number
  tombstones: number
  ignoredEntries: number
}

export interface ScanIssue {
  path?: string
  message: string
}

export interface ScanSnapshot {
  sessions: ClaudeSession[]
  scannedAt: number
  durationMs: number
  roots: StorageRoots
  stats: ScanStats
  issues: ScanIssue[]
}

export interface ProjectUsage {
  projectKey: string
  projectName: string
  projectPath?: string
  sessions: number
  totalSize: number
}

export interface StorageInfo {
  totalSessions: number
  active: number
  /** Claude Desktop archived (isArchived). */
  archived: number
  hiddenInManager: number
  transcriptOnly: number
  metadataOnly: number
  orphan: number
  problems: number
  totalSize: number
  transcriptBytes: number
  sessionDataBytes: number
  otherBytes: number
  topProjects: ProjectUsage[]
  largestSessions: Array<Pick<ClaudeSession, 'id' | 'displayTitle' | 'projectName' | 'totalSize' | 'status'>>
  roots: StorageRoots
  cachePath: string
  scannedAt: number
}

// ---------------------------------------------------------------------------
// Process safety
// ---------------------------------------------------------------------------

export type ClaudeProcessKind = 'desktop' | 'claude-code' | 'unknown'

export interface ClaudeProcessInfo {
  pid: number
  name: string
  executablePath?: string
  kind: ClaudeProcessKind
}

export interface LiveCliSession {
  pid: number
  sessionId: string
  cwd?: string
  status?: string
  name?: string
  entrypoint?: string
  /** Process start time recorded by Claude Code (Windows FILETIME), used to detect PID reuse. */
  procStart?: string
  alive: boolean
}

export interface ProcessStatus {
  checkedAt: number
  supported: boolean
  /** Claude Desktop (or an unidentifiable Claude process) is running. */
  desktopRunning: boolean
  desktopProcesses: ClaudeProcessInfo[]
  claudeCodeProcesses: ClaudeProcessInfo[]
  unknownProcesses: ClaudeProcessInfo[]
  liveSessions: LiveCliSession[]
  error?: string
}

// ---------------------------------------------------------------------------
// Actions
// ---------------------------------------------------------------------------

export type ActionErrorCode =
  | 'CLAUDE_RUNNING'
  | 'SESSION_IN_USE'
  | 'NOT_FOUND'
  | 'NOT_SUPPORTED'
  | 'INVALID_INPUT'
  | 'PATH_REJECTED'
  | 'CHANGED_ON_DISK'
  | 'STALE_PLAN'
  | 'PROTECTED_PATH'
  | 'RECENTLY_WRITTEN'
  | 'IO_ERROR'
  | 'CANCELLED'

export interface ActionResult {
  ok: boolean
  message: string
  code?: ActionErrorCode
  dryRun?: boolean
}

export interface BulkActionResult {
  ok: boolean
  message: string
  results: Array<{ id: string; title: string } & ActionResult>
}

export type PlanItemKind =
  | 'metadata'
  | 'transcript'
  | 'session-data'
  | 'subagent-log'
  | 'file-history'
  | 'session-env'
  | 'tombstone'
  | 'archive-index'
  /** A record in this manager's own data (hidden list, scan cache). Not a Claude file. */
  | 'manager-record'

export type PlanAction = 'delete-file' | 'delete-directory' | 'create-file' | 'update-file' | 'remove-record'

export interface DeletePlanItem {
  kind: PlanItemKind
  action: PlanAction
  path: string
  sizeBytes?: number
  /** Files that will be removed (1 for a file target). */
  fileCount?: number
  /** Directories that will be removed, including the target folder itself. */
  dirCount?: number
  /** For `manager-record` items: which manager store the record lives in. */
  recordType?: 'hidden-list' | 'scan-cache'
  note?: string
}

export interface SessionDeletePlan {
  sessionId: string
  displayTitle: string
  status: SessionStatus
  cliSessionId?: string
  desktopSessionId?: string
  projectName: string
  /** Workspace path; listed under "will not delete". */
  projectPath?: string
  items: DeletePlanItem[]
  totalBytes: number
  totalFiles: number
  totalDirs: number
  /** Paths explicitly kept (workspace, Claude project folder, project memory). */
  willNotDelete: Array<{ path: string; reason: string }>
  /** When set, this session cannot be deleted right now. */
  blockedReason?: string
  blockedCode?: ActionErrorCode
  warnings: string[]
}

export interface DeletePlan {
  /** Unique ID of this plan; the only plan reference the renderer sends back. */
  planId: string
  /** Deterministic SHA-256 of the plan content (targets, sizes, identities). */
  contentHash: string
  createdAt: number
  expiresAt: number
  dryRun: boolean
  bulk: boolean
  /** Sessions that will be deleted. */
  sessions: SessionDeletePlan[]
  /** Sessions that were requested but are blocked and will be skipped. */
  blocked: SessionDeletePlan[]
  /** Global reason that blocks real deletion (e.g. Claude Desktop running). */
  globalBlockedReason?: string
  globalBlockedCode?: ActionErrorCode
  totalBytes: number
  totalItems: number
  totalFiles: number
  totalDirs: number
  /** Phrases accepted in the confirmation box. */
  confirmationPhrases: string[]
  /** Human-readable plan for review/copying (generated by the main process). */
  reportText: string
}

export type DeleteItemOutcome = 'deleted' | 'created' | 'updated' | 'missing' | 'failed' | 'skipped' | 'dry-run'

export interface DeleteItemResult extends DeletePlanItem {
  outcome: DeleteItemOutcome
  error?: string
}

export interface SessionDeleteResult {
  sessionId: string
  displayTitle: string
  outcome: 'deleted' | 'partial' | 'failed' | 'skipped' | 'dry-run'
  items: DeleteItemResult[]
  error?: string
}

export interface DeleteResult {
  ok: boolean
  partial: boolean
  dryRun: boolean
  code?: ActionErrorCode
  message: string
  planId?: string
  /** Dry run only: the reason a real delete would be refused right now. */
  wouldBeBlocked?: string
  sessions: SessionDeleteResult[]
  /** Human-readable report of what was (or would be) done. */
  reportText?: string
}

export type ExportFormat = 'jsonl' | 'info' | 'markdown'

export interface ExportResult {
  ok: boolean
  message: string
  files: string[]
  errors: string[]
  cancelled?: boolean
}

// ---------------------------------------------------------------------------
// Settings / app info
// ---------------------------------------------------------------------------

export type RefreshMode = 'manual' | 'watch' | 'interval'

export interface AppSettings {
  refreshMode: RefreshMode
  refreshIntervalSec: number
  showRawPaths: boolean
  debugMode: boolean
}

export interface AppInfo {
  name: string
  version: string
  isPackaged: boolean
  platform: string
  userDataPath: string
  cachePath: string
  logPath: string
  electronVersion: string
}

export interface LogEntry {
  time: number
  level: 'debug' | 'info' | 'warn' | 'error'
  message: string
}

// ---------------------------------------------------------------------------
// Deletion safety mode (process memory only, never persisted)
// ---------------------------------------------------------------------------

export type SafetyModeReason =
  /** Every launch starts here. */
  | 'startup'
  /** Development run started armed via an explicitly allowed env variable. */
  | 'env-dev'
  | 'armed-in-ui'
  | 'returned-by-user'
  | 'expired'
  /** A real delete ran; arming is single-use. */
  | 'after-delete'

export interface SafetyModeState {
  /** true = SAFE MODE (dry run). false = REAL DELETE ARMED. */
  dryRun: boolean
  reason: SafetyModeReason
  changedAt: number
  armedAt?: number
  /** Armed mode returns to Safe Mode automatically at this time. */
  expiresAt?: number
  armDurationMs: number
  /** e.g. a stale environment variable that was ignored at startup. */
  notice?: string
}

export interface ArmResult extends ActionResult {
  state: SafetyModeState
}
