#!/usr/bin/env node
/**
 * Microsoft Store package (AppX), separate from the GitHub Setup/Portable build.
 *
 *   yarn dist:store        Store submission package → dist/store/
 *                          Requires the Partner Center identity (store/identity.json
 *                          or STORE_* env vars); refuses to build without it.
 *   yarn dist:store:test   Local TEST package with an obviously fake identity →
 *                          dist/store-test/ (…-TEST-NOT-FOR-STORE.appx). Only for
 *                          checking the toolchain/manifest; never submit it.
 *
 * The package is not signed: the Microsoft Store signs submissions. Nothing is
 * uploaded or published.
 */
import { execSync } from 'node:child_process'
import { createHash } from 'node:crypto'
import { copyFileSync, existsSync, readFileSync, rmSync, writeFileSync, mkdirSync } from 'node:fs'
import path from 'node:path'
import {
  ROOT,
  STORE_ASSETS,
  TEST_IDENTITY,
  identityHelp,
  loadStoreIdentity,
  storeBuilderConfig,
  toStorePackageVersion,
  validateStoreIdentity
} from './store-config.mjs'
import { inspectAppx, reviewManifest } from './store-inspect.mjs'

const args = process.argv.slice(2)
const test = args.includes('--test')
const skipBuild = args.includes('--skip-build')

function fail(message, code = 1) {
  console.error(`\n${message}\n`)
  process.exit(code)
}

const pkg = JSON.parse(readFileSync(path.join(ROOT, 'package.json'), 'utf8'))
const storeVersion = toStorePackageVersion(pkg.version)

// 1. Identity: exact Partner Center values, or the clearly fake test identity.
const identity = test ? { ...TEST_IDENTITY } : loadStoreIdentity()
if (!test) {
  const errors = validateStoreIdentity(identity)
  if (errors.length) fail(identityHelp(errors), 2)
}

// 2. Visual assets (generated by `yarn icon` from src/shared/appMark.json).
const assetDir = path.join(ROOT, 'build', 'appx')
for (const [name, [w, h]] of Object.entries(STORE_ASSETS)) {
  const file = path.join(assetDir, name)
  if (!existsSync(file)) fail(`Missing Store asset build/appx/${name}. Run \`yarn icon\`.`)
  const ihdr = readFileSync(file).subarray(16, 24)
  const [fw, fh] = [ihdr.readUInt32BE(0), ihdr.readUInt32BE(4)]
  if (fw !== w || fh !== h) fail(`build/appx/${name} is ${fw}x${fh}, expected ${w}x${h}. Run \`yarn icon\`.`)
}

const config = storeBuilderConfig({ identity, version: pkg.version, test })
const outDir = path.join(ROOT, config.directories.output)
rmSync(outDir, { recursive: true, force: true })
mkdirSync(outDir, { recursive: true })

console.log(`\nMicrosoft Store package ${test ? '(LOCAL TEST — not for submission) ' : ''}v${pkg.version} → package version ${storeVersion}`)
console.log(`  Identity Name : ${identity.identityName}`)
console.log(`  Publisher     : ${identity.publisher}`)
console.log(`  Display name  : ${identity.displayName}\n`)

// 3. Compile (same bundles as the GitHub build; the channel marker comes from packaging metadata).
if (!skipBuild) execSync('yarn build', { cwd: ROOT, stdio: 'inherit', shell: true })

// 4. AppX only, never publishing. Overrides are deep-merged onto electron-builder.yml.
process.env.CSC_IDENTITY_AUTO_DISCOVERY = 'false'
const builder = await import('electron-builder')
const { build, Platform, Arch } = builder.default ?? builder
const manifestCopy = path.join(outDir, 'AppxManifest.xml')
await build({
  projectDir: ROOT,
  targets: Platform.WINDOWS.createTarget(['appx'], Arch.x64),
  publish: 'never',
  config: {
    ...config,
    appxManifestCreated: (file) => copyFileSync(file, manifestCopy)
  }
})

// 5. Verify the package and write the review + checksum next to it.
const artifact = path.join(outDir, config.appx.artifactName)
if (!existsSync(artifact)) fail(`Expected package not found: ${artifact}`)
const inspection = inspectAppx(artifact)
const review = reviewManifest(readFileSync(manifestCopy, 'utf8'), {
  identity,
  storeVersion,
  assets: Object.keys(STORE_ASSETS),
  entries: inspection.entries
})
// The app archive itself: Store channel marker, and no GitHub updater code.
const asar = await import('@electron/asar')
const asarFile = path.join(outDir, 'win-unpacked', 'resources', 'app.asar')
const asarFiles = (asar.default ?? asar).listPackage(asarFile).map((f) => f.replace(/\\/g, '/'))
const packaged = JSON.parse((asar.default ?? asar).extractFile(asarFile, 'package.json').toString())
const extra = [
  ['App metadata distributionChannel is "store"', packaged.distributionChannel === 'store'],
  ['No electron-updater in the Store package', !asarFiles.some((f) => f.includes('/node_modules/electron-updater/'))]
]
for (const [label, ok] of extra) review.text += `\n  ${ok ? 'PASS' : 'FAIL'}  ${label}`
review.ok = review.ok && extra.every(([, ok]) => ok)
writeFileSync(path.join(outDir, 'manifest-review.txt'), review.text + '\n')
const sha = createHash('sha256').update(readFileSync(artifact)).digest('hex')
writeFileSync(path.join(outDir, 'SHA256SUMS.txt'), `${sha}  ${path.basename(artifact)}\n`)

console.log('\n' + review.text)
if (!review.ok) fail('Manifest review FAILED (see above). Do not submit this package.')
console.log(`\nPackage: ${path.relative(ROOT, artifact)}`)
console.log(test ? 'LOCAL TEST package: fake identity, never submit it to the Store.' : 'Ready to upload in Partner Center → Submission → Packages (not uploaded by this script).')
