// Microsoft Store (AppX) packaging configuration: identity, version and the
// electron-builder overrides. Pure functions (no build side effects) so they
// are unit-tested in tests/store.test.ts and reused by dist-store.mjs,
// store-check.mjs and the store-build workflow.
import { createHash } from 'node:crypto'
import { existsSync, readFileSync } from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

export const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..')
export const IDENTITY_FILE = path.join('store', 'identity.json')
export const STORE_OUTPUT = path.join('dist', 'store')
export const STORE_TEST_OUTPUT = path.join('dist', 'store-test')

/** UI locale → Windows package resource language (en / vi / zh-CN UI). */
export const STORE_LANGUAGE_MAP = { en: 'en-US', vi: 'vi-VN', 'zh-CN': 'zh-CN' }

/** Windows 10 2004+: needed for desktop6:FileSystemWriteVirtualization (see store/AppxManifest.template.xml). */
export const STORE_MIN_WINDOWS = '10.0.19041.0'
export const STORE_MAX_TESTED_WINDOWS = '10.0.26100.0'
export const STORE_APPLICATION_ID = 'ClaudeLocalSessionManager'
export const STORE_EXCLUDED_FILES = '!**/node_modules/electron-updater/**/*'

/** Assets electron-builder maps into the package (build/appx/). Generated by `yarn icon` from shared/appMark.json. */
export const STORE_ASSETS = {
  'StoreLogo.png': [50, 50],
  'Square44x44Logo.png': [44, 44],
  'Square150x150Logo.png': [150, 150],
  'Wide310x150Logo.png': [310, 150],
  'SmallTile.png': [71, 71],
  'LargeTile.png': [310, 310],
  'Square44x44Logo.targetsize-16_altform-unplated.png': [16, 16],
  'Square44x44Logo.targetsize-24_altform-unplated.png': [24, 24],
  'Square44x44Logo.targetsize-32_altform-unplated.png': [32, 32],
  'Square44x44Logo.targetsize-44_altform-unplated.png': [44, 44],
  'Square44x44Logo.targetsize-48_altform-unplated.png': [48, 48],
  'Square44x44Logo.targetsize-256_altform-unplated.png': [256, 256]
}

/** Fields and where to find them in Partner Center (Product identity page). */
export const IDENTITY_FIELDS = {
  identityName: { env: 'STORE_IDENTITY_NAME', partnerCenter: 'Package/Identity/Name' },
  publisher: { env: 'STORE_PUBLISHER', partnerCenter: 'Package/Identity/Publisher' },
  publisherDisplayName: { env: 'STORE_PUBLISHER_DISPLAY_NAME', partnerCenter: 'Package/Properties/PublisherDisplayName' },
  displayName: { env: 'STORE_DISPLAY_NAME', partnerCenter: 'the reserved app name (Package/Properties/DisplayName)' },
  storeProductId: { env: 'STORE_PRODUCT_ID', aliases: ['STORE_ID'], partnerCenter: 'Store ID (optional, enables "View in Microsoft Store")' }
}

/** Obviously fake identity for local manifest/packaging tests only. Never submittable. */
export const TEST_IDENTITY = Object.freeze({
  identityName: 'LocalTest.ClaudeLocalSessionManager',
  publisher: 'CN=LOCAL-TEST-NOT-FOR-STORE',
  publisherDisplayName: 'Local test build (not for Store submission)',
  displayName: 'Claude Local Session Manager',
  storeProductId: ''
})

const PLACEHOLDER_RE = /^(todo|tbd|placeholder|example|changeme|xxx+|<.*>|\$\{.*\}|cn=ms|cn=test.*|cn=local-test.*)$/i

/**
 * Store package version from the one canonical version (package.json semver).
 * X.Y.Z → X.Y.Z.0. The fourth part is reserved by the Microsoft Store and must
 * stay 0; every part must fit in 0..65535. Store submissions must increase.
 */
export function toStorePackageVersion(semver) {
  const m = /^(\d+)\.(\d+)\.(\d+)$/.exec(String(semver).trim())
  if (!m) throw new Error(`Store package version needs a plain X.Y.Z version, got "${semver}"`)
  const parts = m.slice(1, 4).map(Number)
  if (parts.some((p) => p > 65535)) throw new Error(`Version parts must be <= 65535: ${semver}`)
  if (parts[0] === 0) throw new Error(`Store package major version must be at least 1: ${semver}`)
  return `${parts.join('.')}.0`
}

/**
 * Windows publisher ID: SHA-256 of the Publisher string (UTF-16LE), first 8
 * bytes, as 13 Crockford base32 characters. Derived, never configured.
 */
export function publisherId(publisher) {
  const hash = createHash('sha256').update(Buffer.from(String(publisher), 'utf16le')).digest()
  const bits = [...hash.subarray(0, 8)].map((b) => b.toString(2).padStart(8, '0')).join('') + '0'
  const alphabet = '0123456789abcdefghjkmnpqrstvwxyz'
  let id = ''
  for (let i = 0; i < 65; i += 5) id += alphabet[parseInt(bits.slice(i, i + 5), 2)]
  return id
}

/**
 * Package family name as Windows/Partner Center compute it from the package
 * Identity Name + Publisher. Compare it with Partner Center → Product
 * identity → Package/Identity/PackageFamilyName before uploading: a single
 * wrong character in the Publisher changes it.
 */
export function packageFamilyName(identityName, publisher) {
  return `${identityName}_${publisherId(publisher)}`
}

/** Read store/identity.json, then apply non-empty STORE_* environment overrides. */
export function loadStoreIdentity({ root = ROOT, env = process.env } = {}) {
  const file = path.join(root, IDENTITY_FILE)
  let fromFile = {}
  if (existsSync(file)) fromFile = JSON.parse(readFileSync(file, 'utf8'))
  const identity = {}
  for (const [key, { env: name, aliases = [] }] of Object.entries(IDENTITY_FIELDS)) {
    const override = [name, ...aliases].map((n) => (typeof env[n] === 'string' ? env[n].trim() : '')).find(Boolean) ?? ''
    identity[key] = override || (typeof fromFile[key] === 'string' ? fromFile[key].trim() : '')
  }
  return identity
}

/** Every problem with the identity, worded so the fix (which Partner Center value) is obvious. */
export function validateStoreIdentity(identity) {
  const errors = []
  const where = (key) => `${IDENTITY_FIELDS[key].partnerCenter} → ${IDENTITY_FIELDS[key].env} or "${key}" in ${IDENTITY_FILE.replace(/\\/g, '/')}`
  const required = ['identityName', 'publisher', 'publisherDisplayName', 'displayName']
  for (const key of required) {
    const v = identity[key]
    if (!v) errors.push(`${key} is missing. Copy ${where(key)}.`)
    else if (PLACEHOLDER_RE.test(v)) errors.push(`${key} "${v}" is a placeholder, not the Partner Center value. Copy ${where(key)}.`)
  }
  const { identityName, publisher, displayName, publisherDisplayName, storeProductId } = identity
  if (identityName && !PLACEHOLDER_RE.test(identityName)) {
    if (identityName.length < 3 || identityName.length > 50 || !/^[A-Za-z0-9.-]+$/.test(identityName)) {
      errors.push(`identityName "${identityName}" is not a valid package name (3–50 characters: letters, digits, "." and "-"). Copy ${where('identityName')}.`)
    }
  }
  if (publisher && !PLACEHOLDER_RE.test(publisher)) {
    if (!/^CN=[^,=]+(,\s*[A-Z]+=[^,=]+)*$/.test(publisher)) {
      errors.push(`publisher "${publisher}" must be the exact distinguished name from Partner Center, e.g. "CN=…". Copy ${where('publisher')}.`)
    }
  }
  if (displayName && displayName.length > 256) errors.push('displayName is longer than 256 characters.')
  if (publisherDisplayName && publisherDisplayName.length > 256) errors.push('publisherDisplayName is longer than 256 characters.')
  if (storeProductId && !/^9[0-9A-Z]{11}$/.test(storeProductId)) {
    errors.push(`storeProductId "${storeProductId}" is not a Store ID (12 characters starting with 9). Leave it empty until Partner Center shows one.`)
  }
  return errors
}

/** Human help printed when the identity is incomplete (no package is built). */
export function identityHelp(errors) {
  return [
    'STORE BUILD BLOCKED WAITING FOR PARTNER CENTER IDENTITY',
    '',
    ...errors.map((e) => `  - ${e}`),
    '',
    'Reserve the app name in Partner Center, open Product management → Product identity,',
    'and copy the values exactly (they are not secrets) into store/identity.json or the',
    'STORE_* environment variables. See docs/MICROSOFT_STORE.md.',
    'No package was created: a package with a wrong identity would be rejected by the Store.'
  ].join('\n')
}

export function storeArtifactName(storeVersion, { test = false } = {}) {
  return test
    ? `Claude-Local-Session-Manager-${storeVersion}-x64-TEST-NOT-FOR-STORE.appx`
    : `Claude-Local-Session-Manager-${storeVersion}-x64.appx`
}

/**
 * electron-builder overrides for the Store package. They are deep-merged onto
 * electron-builder.yml, so the GitHub Setup/Portable configuration is untouched.
 */
export function storeBuilderConfig({ identity, version, test = false }) {
  const storeVersion = toStorePackageVersion(version)
  const languages = Object.values(STORE_LANGUAGE_MAP)
  return {
    directories: { output: test ? STORE_TEST_OUTPUT : STORE_OUTPUT },
    // Appended to electron-builder.yml `files`: the Store package carries no
    // self-updater code at all (the Store channel never loads it anyway).
    files: [STORE_EXCLUDED_FILES],
    extraMetadata: {
      distributionChannel: 'store',
      storeProductId: identity.storeProductId || ''
    },
    appx: {
      identityName: identity.identityName,
      publisher: identity.publisher,
      publisherDisplayName: identity.publisherDisplayName,
      displayName: identity.displayName,
      applicationId: STORE_APPLICATION_ID,
      backgroundColor: 'transparent',
      languages,
      showNameOnTiles: false,
      setBuildNumber: false,
      addAutoLaunchExtension: false,
      minVersion: STORE_MIN_WINDOWS,
      maxVersionTested: STORE_MAX_TESTED_WINDOWS,
      // runFullTrust is always added by electron-builder; this is the only extra one (see the manifest template).
      capabilities: ['unvirtualizedResources'],
      customManifestPath: 'store/AppxManifest.template.xml',
      artifactName: storeArtifactName(storeVersion, { test })
    }
  }
}
